language: php
php:
  - 5.5
  - 5.4
  - hhvm
script: phpunit Test.php
notifications:
  slack:
    secure: "ZRoSwEPB/P0PytZJujmVPlbzCZuLp4WdnN6PEt3N/MjYFOuU/LgwKk6fGJ2vY3/ikTJzjWwbb9xvjMUNab2rEvGQZWRamWXG9vLLdZ9Juw4BmDw6x52+aQi7+b1AgMv7+RBl3qkYTbIIixZ5Oof/DmC/goT4OmM1xiHySgr4wQzyrPxOS9KGrskDnvalTBlLO//JF/xAlp5S+IVKkPNKPoMDVEoXEN/gdfIEmasHdQJ3+Wu+rjMxDZSCrNPlF1vhD92XEikHFNgS9nCDYjRQpuP/JPlNQp3HqYtQeVFqIJG7E9v9gGFY0ay2EpzerVziRbHp1o0oujFtSBa4eXAem7zTZ13SvVlCIjr/InPbS4woG1FRmyPtjbw09YVcH7qkuFkOmsiVFWKKpS1X95DuxLoC1kZ5jHJesENl93lhb5pDgdyzaAN0l2A/k4mkvNqUk+bhVWzzX2Ohr2CtJ0Llt2nzWXC/2xK8ZqMzOM9s/EfizUZ9uZno5bcc624VTZgyfyZdHtValtYQjFSGeQbBh/KUKxLU3TGmKrpxUF6KRYQtpsa5tUJdCEiGato3YTCsW5X/QM6yxgyoELsPPguSGn4+P7aeC5zJ17o8hruYyqqlRNfMe7TEtnYSIBtURdCflQMU1fqt2ctvdVGccFjpHicZLtgZwgKPm7QH5ctGw0Q="
